carmen-ruby/carmen

locale/overlay/en/world.yml

Diego Garcia was not included. Its sovereignty is disputed and generally accepted to be part of UK, but is included in other locales, and the ISO recognizes it as an auxiliary area, granted an official code an designation to be recognized by other nations.

Added Diego Garcia

---

lib/carmen/region.rb

Prior to this, #load_subregions returned an empty array if there were no subregions. But there is no reason the calling code should have to check the return type before operating on the return value.

Always return a RegionCollection from #subregions

---

iso_data/overlay/world.yml

This overlay incorrectly override iso data for SG here. The numeric code for SG should be 702 (https://en.wikipedia.org/wiki/ISO_3166-1).
I think this overlay was meant for [SX](https://github.com/jim/carmen/blob/master/iso_data/base/world.yml#L842-L844) instead of `SG`.
I checked the iso data for `SX` is already fixed, and thus this is not needed anymore.

Delete overlay for SG as its numeric code should be 702

---

iso_data/base/world/gb.yml
locale/base/en/world/gb.yml

For consistency reasons, I think all subdivisions of Yorkshire should be included. I have added South and West Yorkshire to complement the East and North divisions currently available.

Add subdivisions for Yorkshire, GB

---

lib/carmen/region.rb
spec/carmen/country_spec.rb
spec/carmen/region_spec.rb

Adding robustness regarding #179 cc @jbourassa

Ensure regions cannot be modified outside gem

---

README.md
lib/carmen/region_collection.rb
spec/carmen/region_collection_spec.rb

This PR implements a `Carmen::RegionCollection#typed` method for finding all subregions with a specific type.

Allow filtering subregions by type

---

lib/carmen/country.rb
lib/carmen/region.rb

Adds a generic method to_hash to Region and Country classes that can be used standalone or with Rails JSON Serializer.
Subregions can be excluded from the JSON by using standard notation `region.as_json(except: :subregions)`

Add serializers friendly to_hash. Fixes #209

---

carmen.gemspec
script/update_data.rb

Running this locally generates data that appears to be correct. After going through some of the countries and their updated subregions "by hand" I am confident that this is working as expected. For example, running this locally will pick up and correctly build YAML for the [changes to France's subregions as described in this issue](https://github.com/carmen-ruby/carmen/issues/228).
The location and format of the ISO data has changed. The data is
available in plain JSON.
The fundamental data structure that is used by Carmen to build the YAML
files is not changed by this PR. This only tweaks the intermediary
step of getting the information from the Debian repository into the data
structure that Carmen needs.
ISO country data:
https://anonscm.debian.org/git/pkg-isocodes/iso-codes.git/plain/da …

Fix data update script

---

iso_data/overlay/world/in.yml
locale/base/en/world/in.yml
locale/overlay/en/world/in.yml

Corrected ISO code for Telangana state in India - https://en.wikipedia.org/wiki/ISO_3166-2:IN#Current_codes

Fixed code for Telangana state in India, added locale entry

---

iso_data/overlay/world/bm.yml
locale/overlay/en/world/bm.yml

Adds support for the 9 parishes of Bermuda.
The [official ISO 3166 for Bermuda](https://www.iso.org/obp/ui/#iso:code:3166:BM) confirms there are 9 parishes, but states, "which is not relevant for this part of ISO 3166". 
I was able  to get the ISO codes for the parishes from http://www.statoids.com/ubm.html:
This same data is also in ["Administrative Subdivisions of Countries: A Comprehensive World Reference" by Gwillim Law](https://books.google.com/books?id=nXCeCQAAQBAJ&pg=PA53&lpg=PA53).
I tested these changes from the console:
```
» bundle exec rake console
2.2.3 :001 > bermuda = Carmen::Country.coded('bm')
=> <#Carmen::Country name="Bermuda">
2.2.3 :002 > bermuda.subregions.map(&:name).sort
=> ["Devenshire", "Hamilton", "Paget", "Pembroke", "Saint George's", "Sandys", "Smiths", …
```

Add Bermuda parishes

---

iso_data/overlay/world.yml
spec/carmen/sanity_spec.rb

According to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements), 'PR' is a country code for Puerto Rico.
This was removed because it is an unincorporated territory of the United
States - which is irrelevant. If the ISO lists 'PR' as a valid country
code, we should treat it as such.
Resolves #214.

Revert removing Puerto Rico as a country code

---

locale/base/en/world/be.yml
locale/overlay/en/world/be.yml

This was supposed to be part of #215, but the modifications were made
directly to the base layer. The base layer gets overwritten each time
the data update script is run.

Fix English translations for Belgian regions

---

CHANGELOG.md

I didn't include a reference to each data change that was made since v1.0.3. I think in the future PRs should include a CHANGELOG entry. We could possibly have two headings for new versions in the CHANGELOG, "Code changes" and "Data changes" (or something along those lines).
Once this and #238 are merged I will update the version and push a release to RubyGems.

Update CHANGELOG for 1.1.0

---

README.md

The carmen-rails library has not been updated in four years, and was
stable for Rails 3. We shouldn't be directing Rails users to that
repository. If there ever comes a time that it is maintained again we
can add it back.

Remove carmen-rails notice from README

---

lib/carmen/region.rb

Replace `File.exists?` with `File.exist?` as per deprecation warning here: https://ruby-doc.org/core-2.2.0/File.html#method-c-exists-3F

remove deprecation warning

---

CHANGELOG.md
iso_data/overlay/world/ma.yml
iso_data/overlay/world/ma/01.yml
iso_data/overlay/world/ma/02.yml
iso_data/overlay/world/ma/03.yml
iso_data/overlay/world/ma/04.yml
iso_data/overlay/world/ma/05.yml
iso_data/overlay/world/ma/06.yml
iso_data/overlay/world/ma/07.yml
iso_data/overlay/world/ma/08.yml
iso_data/overlay/world/ma/09.yml
iso_data/overlay/world/ma/10.yml
iso_data/overlay/world/ma/11.yml
iso_data/overlay/world/ma/12.yml
locale/overlay/en/world/ma.yml
locale/overlay/en/world/ma/01.yml
locale/overlay/en/world/ma/02.yml
locale/overlay/en/world/ma/03.yml
locale/overlay/en/world/ma/04.yml
locale/overlay/en/world/ma/05.yml
locale/overlay/en/world/ma/06.yml
locale/overlay/en/world/ma/07.yml
locale/overlay/en/world/ma/08.yml
locale/overlay/en/world/ma/09.yml
locale/overlay/en/world/ma/10.yml
locale/overlay/en/world/ma/11.yml
locale/overlay/en/world/ma/12.yml

Update Moroccan regions and subregions to match the new standard (after 2015), and because of the absence of the new iso codes, I used the last two digit of the non-official [HASC](http://www.statoids.com/ihasc.html) codes.
Fix: #225 
------------------------------------------
Before submitting the PR please make sure that you have done the following:

Update Moroccan regions and their sub regions

---

CHANGELOG.md
iso_data/overlay/world/gb.yml
locale/overlay/en/world/gb.yml

This came up because we use carmen to populate a "subregion" dropdown that is loaded after a user selects a country. We had several people write in about the UK list not being accurate.
[Middlesex](https://en.wikipedia.org/wiki/Middlesex) is a "Historic County" and [not ISO-recognized as a subregion](https://www.iso.org/obp/ui/#iso:code:3166:GB). [Wiltshire](https://en.wikipedia.org/wiki/Wiltshire) is a "Unitary Authority" and [already in the base library](https://github.com/carmen-ruby/carmen/blob/cd3e696c67c61d81850e1a057ade5abe12a66454/locale/overlay/en/world/gb.yml#L7-L8). Even if their classifications had been corrent, the overlays removed had placed them at the wrong level in the region/subregion yaml hierarchy.
Before: 
```ruby
> uk = Carmen::Country.named('United Kingdom')
> …
```

Remove UK overlays for Middlesex and Wiltshire

---

.travis.yml
carmen.gemspec
spec/carmen/country_spec.rb
spec/carmen/overlay_spec.rb
spec/carmen/region_spec.rb
spec/spec_helper.rb

We were asking for 2.6.1 specifically which was released in September
2001. We have a relatively basic test suite and I'm only seeing a few
deprecation warnings when I upgrade locally.
Our PR Travis checks were failing when running 2.6.1.
I would have split the last commit into a separate PR to make it clear that we aren't supporting EOL versions, but all of these changes are needed to get a green status check.

Use the most recent version of minitest

---

CHANGELOG.md
locale/overlay/bn/world.yml
locale/overlay/en/world.yml
locale/overlay/es/world.yml
locale/overlay/it/world.yml
locale/overlay/pl/world.yml
locale/overlay/th/world.yml

In February 2019 the former Yugoslav Republic of Macedonia officially changed its name to "Republic of North Macedonia".
This PR updates the country name.

Change Macedonia to North Macedonia

---

lib/carmen/querying.rb

In activesupport 6.1 the `normalize` method will be deprecated 
`DEPRECATION WARNING: ActiveSupport::Multibyte::Chars#normalize is deprecated and will be removed from Rails 6.1. Use #unicode_normalize(:nfkc) instead.`
This PR simply applies the suggested change to use `String::unicode_normalize` which was introduced in Ruby 2.2, which by the look of the travis config you assume to be > 2.3 anyway

Fix normalize deprecation warning

---

.travis.yml
carmen.gemspec

There was a failure with Ruby 2.5.0 trying to `require` URI::Generic. This happened inside rake, and this commit is an attempt to avoid that by picking any rake available.

gemspec: Unpin rake

---

Gemfile

This is a trivial change: use `https` to connect to rubygems.org.

Gemfile: use https:// to connect to rubygems.org
