- locale/overlay/ja/world.yml
- locale/overlay/jp/world.yml
Add translations for Japanese prefectures and correct the locale namespace from jp to ja
Tested and confirmed working
> Add jp prefectures in ja

- iso_data/overlay/world/gb.yml
- locale/overlay/en/world/gb.yml
Would like to add wiltshire province in UK.
https://www.iso.org/obp/ui/#iso:code:3166:GB
> Add wiltshire province

- iso_data/overlay/world/bd.yml
- iso_data/overlay/world/in.yml
- locale/overlay/en/world/bd.yml
- locale/overlay/en/world/in.yml
Closes #151 and #163.
@CDainMiller, @jim I saw these lingering PRs and thought I'd better familiarize myself by resolving them.  Would appreciate an additional set of eyes to make sure I understood the "Contributing Data" documentation.
> Add States & Codes

- iso_data/overlay/world/id/ka.yml
- locale/overlay/en/world/id/ka.yml
Adding [Kalimantan Utara](http://id.wikipedia.org/wiki/Daftar_provinsi_di_Indonesia#Kalimantan_Utara), new province in Indonesia.
> Add Kalimantan Utara to ID's province

- .travis.yml
Fix issues with bundler & 1.9.3 on travis-ci
> Update bundle before install

- spec/carmen/sanity_spec.rb
I noticed the test was updated from 249 to 248 countries in e3a846c456ca8991450b443cdf166cdfade1290e.
> Update number of countries in spec description

- .travis.yml
Updating travis build config to build against latest ruby version.
> Add latest ruby versions & use latest patches

- README.md
Proposal for a small cleanup of the README if that is okay for you @jim.
Remove "new" 1.0 release notice (it was 2-3 years ago)
Remove 1.8 notice
Remove 0.2 branch notice
You can see [a preview here](https://github.com/didacte/carmen/blob/feature/readme-clean/README.md).
> Update README with current status

- locale/overlay/cs/world.yml
I've fixed some errors I've found in the overlay and added missing countries in cs world overlay
> Fix and Add missing countries in Czech (cs) world overlay

- locale/overlay/ja/world/ru.yml
Hello again!
Translating one of my projects to Japanese and need to have a select box with my region's names in Japanese. So, extracted list from Wikipedia and created this PR.
Source: https://ja.wikipedia.org/wiki/ISO_3166-2:RU
> Added translations of Russian regions to Japanese

- README.md
- lib/carmen/country.rb
- spec/carmen/country_spec.rb
This pull request extends #125 allowing not only access country's numeric code value but also allows to search countries by numeric code.
> Add country search by numeric code

- locale/overlay/en/world.yml
Update for [210](https://github.com/jim/carmen/pull/210/) pull request
> fix Russia names

- spec/carmen/sanity_spec.rb
I missed changing this for #233. In the future PRs will be forced to
pass Travis before getting merged so that silly me can't miss things
like this.
> Change total number of countries to 249 in spec

- iso_data/base/world/mx.yml
- locale/base/en/world/mx.yml
Info: https://en.wikipedia.org/wiki/Mexico_City
> Update DF on MX to actual status

- lib/carmen/querying.rb
- spec/carmen/region_spec.rb
- spec_data/data/world/oc.yml
- spec_data/locale/en/world/oc.yml
fixes #222 : names similarities detected space and dash (@raj)
> fixes #222 : names similarities detected space and dash (@raj)

- README.md
Jim moved carmen to the carmen-ruby organization.
> Point build icon link to new repository

- .github/PULL_REQUEST_TEMPLATE.md
My automatic line breaks at 80 characters within vim makes the PR
template look terrible on the web.
> Fix formatting in the PULL_REQUEST_TEMPLATE

- script/update_data.rb
I don't know for what reason but the location of the ISO data was moved
to this new location. It is in the same format, so we are all good.
------------------------------------------
Before submitting the PR please make sure that you have done the following:
changes](https://github.com/carmen-ruby/carmen/wiki/Contributing-Data) if this
PR modifies geographic data
> Update the location of the ISO data

- README.md
This PR changes the build badges to SVG for sharper readability ✨
> chore: README: Use SVG badge

- CHANGELOG.md
- iso_data/overlay/world/bs.yml
- locale/overlay/en/world/bs.yml
Hi,
I added the New Providence district based in the issue https://github.com/carmen-ruby/carmen/issues/280.
Tks!
Alexandre C Martins
------------------------------------------
* [ x ] I have read the [Wiki on how to make geographic changes](https://github.com/carmen-ruby/carmen/wiki/Contributing-Data) if this PR modifies geographic data
* [ x ] I have added a CHANGELOG entry if appropriate
> Adding New Providence (Bahamas) district
